### PR TITLE
GAS Improved

### PR DESCRIPTION
**Pull request by v30xy**
GAS but improved. Inspired from [GAS](https://github.com/Jonyk56/GAS).

### CODE REVIEW

**Comment by marc2332** [comment]
This is 99% copy-paste code. I am not going to accept this.

Original:
image

Yours:
image

**Comment by v30xy** [comment]
As i said, just removed menu _(replaced with status bar button) _and decreased timestamp. Old GAS not working on me so i did one working.

**Comment by v30xy** [comment]
Also im thinking new feature about this plugin.

**Comment by marc2332** [comment]
> 
> 
> As i said, just removed menu _(replaced with status bar button)_ and decreased timestamp. Old GAS not working on me so i did one working.

I would rather contribute to it in such case

**Pull request closed without merging**
