### PR TITLE
Added patch to store

### PR DESCRIPTION
**Pull request by DJN1**
I think this should do it. Let me know if this is the fix.

Thanks,
David

### CODE REVIEW

**Comment by DJN1** [comment]
I just updated the patch and the link. If possible you can merge this, or I can create a new PR with the same changes.

**Comment by marc2332** [comment]
I just added it back :tada:

But be aware you didn't apply my fix into your [repository](https://github.com/DJN1/Graviton-Shades-of-Purple/blob/master/shades-of-purple.css)

What my fix does is wrapping all the CSS selectors inside one (.cm-s-shades-of-purple)
Example:
```css 
//Good✅
.cm-s-shades-of-purple .cm-something {
     whatever: 'cool';
}
```
```css
//Bad 💢
.cm-s-shades-of-purple.cm-something {
     whatever: 'bad';
}
```
```css
//Bad 💢
.cm-something.cm-s-shades-of-purple {
     whatever: 'bad';
}
```

**Comment by DJN1** [comment]
Ohh ok. Now I understand the fix. I have applied that fix now. My apologies for all the problems.

**Comment by marc2332** [comment]
No problem! I appreciate that you made a theme for Graviton. Seriously!

😄

**Pull request closed without merging**
